<!DOCTYPE html>
<html>
    <head>
        <title>Resultado</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>

        <div class='container'>
            <div class="row">

                <div class="col-md-12 mt-2">
                    <?php if($error): ?>
                        <div class="alert alert-danger" role="alert">
                            <ul>
                                <li><?= $errorMessage; ?></li>
                                <?php foreach($errors as $error): ?>
                                    <li><?= $error; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                    <a href="/index.php" class="btn btn-primary">← Enviar novamente o arquivo</a>
                </div>

                <?php if(!$error): ?>
                    <div class="col-md-12 mt-2">
                        <div class="alert alert-success" role="alert">
                            Arquivo processado com sucesso!
                        </div>
                        <h1>Resultado</h1>
                        <ul class="list-group">
                            <?php foreach($casesResult as $key => $case): ?>
                                <li class="list-group-item"><?= ($key+1).'° - ' . $case; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>